name: flash_botany
description: A cross-platform plant family education.
publish_to: "none"
version: 1.0.1+5

environment:
  sdk: ^2.17.0-0
dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.0.4
  adaptive_components: ^0.0.3
  adaptive_navigation: ^0.0.5
  animations: ^2.0.2
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.1.2
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.10.0
  freezed_annotation: ^2.0.3
  freezed: ^2.0.3+1
  json_serializable: ^6.5.2
  json_annotation: ^4.7.0
  google_fonts: ^2.3.1
  snapping_sheet: ^3.1.0
  flutter_svg: ^1.1.0
  url_launcher: ^6.1.2
  card_swiper: ^2.0.4
  cached_network_image: ^3.2.1
  shimmer_animation: ^2.1.0+1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  injectable: ^1.5.3
  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  persistent_bottom_nav_bar: ^5.0.2
  introduction_screen: ^3.1.8

dev_dependencies:
  build_runner: ^2.1.7
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  analyzer: ^5.2.0
  drift_dev: ^2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/flower_shadow_ios.png"
  adaptive_icon_foreground: "assets/images/flower_fg.png"
  adaptive_icon_background: "assets/images/flower_bg.png"
  web:
    generate: true
    image_path: "assets/images/flower_web.png"
    background_color: "#FFAABBCC"
    theme_color: "#FFCCBBAA"

flutter_native_splash:
  image: "assets/images/flower_fg.png"
  color: "#2f312d"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
